trigger:
- main

pool:
  name: dhurander

stages:
- stage: DockerBuild

  jobs:
  - job: BuildAndPush

    steps:

    - checkout: self
      submodules: recursive

    - task: PowerShell@2
      displayName: 'Check Dockerfile Path'
      inputs:
        targetType: 'inline'
        script: |
          $path = "$(Build.SourcesDirectory)\axion-ingestion-service"

          Write-Host "====================================="
          Write-Host "Ingestion Service Folder:"
          Write-Host $path

          Write-Host "====================================="
          Get-ChildItem $path -Force

          Write-Host "====================================="
          Write-Host "Dockerfile check:"

          if (Test-Path "$path\Dockerfile") {
              Write-Host "Dockerfile FOUND"
              Get-Item "$path\Dockerfile"
          }
          else {
              Write-Host "Dockerfile NOT FOUND"
              Get-ChildItem $path -Recurse -Force
              exit 1
          }

    - task: Docker@2
      displayName: 'Docker Login'
      inputs:
        containerRegistry: 'docker-rg'
        command: 'login'

    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: 'docker-rg'
        repository: 'ankitlodhi11.axionpipeline'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/axion-ingestion-service/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/axion-ingestion-service'
        tags: |
          $(Build.BuildId)