trigger:
- main

pool:
  name: dhurander

stages:

# =========================================================
# BUILD AND PUSH IMAGE
# =========================================================

- stage: Build
  displayName: Build and Push to ACR

  jobs:
  - job: DockerBuild
    displayName: Build Docker Image

    steps:

    # Checkout source code
    - checkout: self

    # Debug - verify Dockerfile location
    - powershell: |
        Write-Host "Build Sources Directory:"
        Write-Host "$(Build.SourcesDirectory)"

        Write-Host ""
        Write-Host "Repository files:"
        Get-ChildItem "$(Build.SourcesDirectory)" -Recurse -File |
          Select-Object FullName

        Write-Host ""
        Write-Host "Checking Dockerfile:"
        Test-Path "$(Build.SourcesDirectory)/axion-telemetry-query-service/Dockerfile"
      displayName: 'Verify Dockerfile'

    # Build and Push Docker Image
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: 'docker-rg'
        repository: 'telemetry'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/axion-telemetry-query-service/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/axion-telemetry-query-service'
        tags: |
          $(Build.BuildId)


# =========================================================
# DEPLOY TO AKS
# =========================================================

- stage: Deploy
  displayName: Deploy to AKS

  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: AKSDeploy
    displayName: Deploy to AKS

    steps:

    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy Deployment YAML
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'axionaks'
        manifests: |
          $(Build.SourcesDirectory)/axion-telemetry-query-service/Manifests/*.yaml
        containers: |
          grugram.azurecr.io/telemetry:$(Build.BuildId)

