apiVersion: apps/v1
kind: Deployment
metadata:
  name: axionsimulator  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axionsimulator
  template:
    metadata:
      labels:
        app: axionsimulator 
    spec:
      containers:
        - name: simulatorcontainer
          image: axiontest.azurecr.io/simulater:v1
          env:
            - name: API_URL
              value: "http://axioningestion-service:8000/api/v1/telemetry/ingest"

            - name: INTERVAL_SECONDS
              value: "5"  
          