apiVersion: apps/v1
kind: Deployment
metadata:
  name: axioningestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axioningestion
  template:
    metadata:
      labels:
        app: axioningestion
    spec:
      containers:
        - name: ingestioncontainer
          image: grugram.azurecr.io/ingestion:IMAGE_TAG
          ports:
            - containerPort: 8000
          