apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui 
    spec:
      containers:
        - name: axion-uicontainer
          image: axiontest.azurecr.io/axion-ui:v1
          ports:
            - containerPort: 80
          
