apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-telemetry
  template:
    metadata:
      labels:
        app: axion-telemetry
    spec:
      containers:
        - name: axion-telemetrycontainer
          image: axiontest.azurecr.io/telemetry:v1
          ports:
            - containerPort: 8000
